highlighter: rouge
github: [Repository metadata]

baseurl: "http://www.doggroomingbygentlehands.com"
livereload: true

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true

# Plugins
#plugins: 
#  - jekyll-redirect-from
#  - jekyll-sitemap