highlighter: rouge
github: [Repository metadata]

baseurl: "https://kristenzirkler.github.io/gentlehands-site"
livereload: true

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true

# Plugins
plugins: 
  - jekyll-redirect-from
  - jekyll-sitemap